INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'FUNCTION_COLUMNS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -22, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'CONSTANTS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -23, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'SEQUENCES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -9, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'RIGHTS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -12, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'TRIGGERS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -25, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'CATALOGS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -6, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'CROSS_REFERENCES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -20, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'SETTINGS', 'SYSTEM TABLE', 'CACHED', null, '', 9223372036854775807, -7, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'FUNCTION_ALIASES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -13, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'VIEWS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -18, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'TYPE_INFO', 'SYSTEM TABLE', 'CACHED', null, '', 329, -5, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'CONSTRAINTS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -21, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'COLUMNS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -2, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'LOCKS', 'SYSTEM TABLE', 'CACHED', null, '', 9223372036854775807, -27, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'KEY_COLUMN_USAGE', 'SYSTEM TABLE', 'CACHED', null, '', 329, -32, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'DOMAINS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -24, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'SCHEMATA', 'SYSTEM TABLE', 'CACHED', null, '', 329, -14, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'COLUMN_PRIVILEGES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -16, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'HELP', 'SYSTEM TABLE', 'CACHED', null, '', 329, -8, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'SESSION_STATE', 'SYSTEM TABLE', 'CACHED', null, '', 9223372036854775807, -28, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'TABLE_PRIVILEGES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -15, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'REFERENTIAL_CONSTRAINTS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -33, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'TABLE_TYPES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -4, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'TABLES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -1, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'QUERY_STATISTICS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -29, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'ROLES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -11, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'SESSIONS', 'SYSTEM TABLE', 'CACHED', null, '', 9223372036854775807, -26, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'IN_DOUBT', 'SYSTEM TABLE', 'CACHED', null, '', 9223372036854775807, -19, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'USERS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -10, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'COLLATIONS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -17, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'SYNONYMS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -30, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'TABLE_CONSTRAINTS', 'SYSTEM TABLE', 'CACHED', null, '', 329, -31, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'INFORMATION_SCHEMA', 'INDEXES', 'SYSTEM TABLE', 'CACHED', null, '', 329, -3, null, 'org.h2.table.MetaTable', 1000);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'PUBLIC', 'STUDY_PLAN', 'TABLE', 'MEMORY', 'CREATE MEMORY TABLE "PUBLIC"."STUDY_PLAN"(
    "ID" INT NOT NULL,
    "SUBJECT_ID" INT NOT NULL,
    "EXAM_TYPE_ID" INT NOT NULL
)', '', 263, 10, null, 'org.h2.mvstore.db.MVTable', 8);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'PUBLIC', 'STUDENT', 'TABLE', 'MEMORY', 'CREATE MEMORY TABLE "PUBLIC"."STUDENT"(
    "ID" INT NOT NULL,
    "SURNAME" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "SECOND_NAME" TEXT NOT NULL,
    "STUDY_GROUP_ID" INT
)', '', 180, 4, null, 'org.h2.mvstore.db.MVTable', 0);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'PUBLIC', 'STUDY_GROUP', 'TABLE', 'MEMORY', 'CREATE MEMORY TABLE "PUBLIC"."STUDY_GROUP"(
    "ID" INT NOT NULL,
    "NAME" TEXT NOT NULL
)', '', 0, 3, null, 'org.h2.mvstore.db.MVTable', 0);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'PUBLIC', 'JOURNAL', 'TABLE', 'MEMORY', 'CREATE MEMORY TABLE "PUBLIC"."JOURNAL"(
    "ID" INT NOT NULL,
    "STUDENT_ID" INT NOT NULL,
    "STUDY_PLAN_ID" INT NOT NULL,
    "IN_TIME" BIT NOT NULL,
    "COUNT" INT DEFAULT 0,
    "MARK_ID" INT NOT NULL
)', '', 225, 18, null, 'org.h2.mvstore.db.MVTable', 0);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'PUBLIC', 'SUBJECT', 'TABLE', 'MEMORY', 'CREATE MEMORY TABLE "PUBLIC"."SUBJECT"(
    "ID" INT NOT NULL,
    "NAME" TEXT NOT NULL,
    "SHORT_NAME" TEXT NOT NULL
)', '', 239, 8, null, 'org.h2.mvstore.db.MVTable', 7);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'PUBLIC', 'MARK', 'TABLE', 'MEMORY', 'CREATE MEMORY TABLE "PUBLIC"."MARK"(
    "ID" INT NOT NULL,
    "NAME" TEXT NOT NULL,
    "VALUE" TEXT NOT NULL
)', '', 277, 17, null, 'org.h2.mvstore.db.MVTable', 7);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, STORAGE_TYPE, SQL, REMARKS, LAST_MODIFICATION, ID, TYPE_NAME, TABLE_CLASS, ROW_COUNT_ESTIMATE) VALUES ('DEFAULT', 'PUBLIC', 'EXAM_TYPE', 'TABLE', 'MEMORY', 'CREATE MEMORY TABLE "PUBLIC"."EXAM_TYPE"(
    "ID" INT NOT NULL,
    "TYPE" TEXT NOT NULL
)', '', 247, 9, null, 'org.h2.mvstore.db.MVTable', 4);