INSERT INTO PUBLIC.MARK (ID, NAME, VALUE) VALUES (1, 'Отлично', '5');
INSERT INTO PUBLIC.MARK (ID, NAME, VALUE) VALUES (2, 'Хорошо', '4');
INSERT INTO PUBLIC.MARK (ID, NAME, VALUE) VALUES (3, 'Удовлетворительно', '3');
INSERT INTO PUBLIC.MARK (ID, NAME, VALUE) VALUES (4, 'Неудовлетворительно', '2');
INSERT INTO PUBLIC.MARK (ID, NAME, VALUE) VALUES (5, 'Зачет', 'з');
INSERT INTO PUBLIC.MARK (ID, NAME, VALUE) VALUES (6, 'Незачет', 'н');
INSERT INTO PUBLIC.MARK (ID, NAME, VALUE) VALUES (7, 'Неявка', '');