INSERT INTO PUBLIC.STUDY_PLAN (ID, SUBJECT_ID, EXAM_TYPE_ID) VALUES (1, 1, 1);
INSERT INTO PUBLIC.STUDY_PLAN (ID, SUBJECT_ID, EXAM_TYPE_ID) VALUES (2, 1, 4);
INSERT INTO PUBLIC.STUDY_PLAN (ID, SUBJECT_ID, EXAM_TYPE_ID) VALUES (3, 2, 1);
INSERT INTO PUBLIC.STUDY_PLAN (ID, SUBJECT_ID, EXAM_TYPE_ID) VALUES (4, 3, 1);
INSERT INTO PUBLIC.STUDY_PLAN (ID, SUBJECT_ID, EXAM_TYPE_ID) VALUES (5, 4, 2);
INSERT INTO PUBLIC.STUDY_PLAN (ID, SUBJECT_ID, EXAM_TYPE_ID) VALUES (6, 5, 1);
INSERT INTO PUBLIC.STUDY_PLAN (ID, SUBJECT_ID, EXAM_TYPE_ID) VALUES (7, 6, 2);
INSERT INTO PUBLIC.STUDY_PLAN (ID, SUBJECT_ID, EXAM_TYPE_ID) VALUES (8, 7, 1);