INSERT INTO PUBLIC.EXAM_TYPE (ID, TYPE) VALUES (1, 'Экзамен');
INSERT INTO PUBLIC.EXAM_TYPE (ID, TYPE) VALUES (2, 'Зачет');
INSERT INTO PUBLIC.EXAM_TYPE (ID, TYPE) VALUES (3, 'Зачет с оценкой');
INSERT INTO PUBLIC.EXAM_TYPE (ID, TYPE) VALUES (4, 'Курсовая');